services:
  app:
    container_name: fastapi-app
    build:
      context: ./app
      dockerfile: Dockerfile

    volumes:
     - ./app:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env

    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13
    env_file:
     - ./app/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

